message: Hello lord Kevin

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
        
        

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:500/eureka/
  instance:
     hostname: localhost
