message: Hello lord Kevin

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
        
        

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:500/eureka/
