message: Hello lord Kevin

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
        
spring:
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://eureka-0.eureka:500/eureka
#       defaultZone: http://localhost:500/eureka/
  instance:
     hostname: localhost
